services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - express_app

  express_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    expose:
      - "3000"
